.\"
.\" iiview - Thumb viewer application
.\"
.Dd August 06, 2003
.Dt IIVIEW 1
.Os
.Sh NAME
.Nm iiview
.Nd Thumb Viewer Application
.Sh SYNOPSIS
.Nm
.Ar [file]
.Sh DESCRIPTION
.Nm
IIViewer is an application for X. It allows you to display
pictures in a directory as thumbnails. Selected images can then be
shown in full size. It reads the most common graphic formats.
.Sh OPTIONS
The following command line arguments are supported:
.Bl -tag -width indent
.It Ar file
the picture to show directly (without thumb-screen)
.Sh AUTHOR
.An nakal
.Sh BUGS
IIView had some problems with resolutions and bpp-values.
Please keep an eye open. Any help is welcome.
You can always complain about incompatibilities
on my project site
.Bf -emphasis
https://github.com/nakal/iiview
.Ef
